export const PROJECTS = [
  {
    num: "01",
    category: "Frontend",
    title: "Legrand Web Services",
    description: "Site web vitrine de l'agence Legrand Web Services.",
    stack: ["HTML 5", "CSS 3", "JavaScript"],
    image: "/assets/work/main-web-lws.png",
    live: "https://legrandwebservices.com/",
    github: "https://legrandwebservices.com",
  },
  {
    num: "02",
    category: "Web App",
    title: "GSH Financement",
    description: "Plateforme de financement participatif.",
    stack: ["Laravel", "Bootstrap", "MySQL"],
    image: "/assets/work/thumb6.png",
    live: "https://gsh.switch-maker.net/",
    github: "https://gsh.switch-maker.net/",
  },
  {
    num: "03",
    category: "Portfolio",
    title: "Zabre Portfolio",
    description: "Portfolio personnel.",
    stack: ["Next.js", "Tailwind CSS", "Node.js", "Vercel", "GitHub", "Node Mailer"],
    image: "/assets/work/thumb7.png",
    live: "https://zabre-portfolio.vercel.app",
    github: "https://github.com/outis62/zabre-portfolio",
  },
  {
    num: "04",
    category: "Web App",
    title: "Gestion Universitaire",
    description: "Plateforme de gestion scolaire et universitaire.",
    stack: ["Laravel", "Livewire", "MySQL", "Bootstrap"],
    image: "/assets/work/thumb11.png",
    live: "",
    github: "https://github.com/outis62/Gestion-univ-livewire",
  },
  {
    num: "05",
    category: "WordPress",
    title: "Fondation Y2MA",
    description: "Site web de la fondation Y2MA.",
    stack: ["WordPress", "MySQL"],
    image: "/assets/work/thumb8.png",
    live: "https://fondationy2ma.com/",
    github: "https://fondationy2ma.com/",
  },
  {
    num: "06",
    category: "WordPress",
    title: "SAD Architecture",
    description: "Site web de SAD Architecture.",
    stack: ["WordPress", "MySQL", "Hostinger"],
    image: "/assets/work/thumb9.png",
    live: "https://sadarchitecture.com/",
    github: "https://sadarchitecture.com/",
  },
  {
    num: "07",
    category: "Full stack",
    title: "JVO Global Investments",
    description: "Site web de JVO Global Investments.",
    stack: ["WordPress", "MySQL", "Hostinger"],
    image: "/assets/work/thumb11.png",
    live: "https://jvoglobal.com/",
    github: "https://jvoglobal.com/",
  },
  {
    num: "08",
    category: "Full stack",
    title: "Verduxe",
    description: "Site web de Verduxe.",
    stack: ["WordPress", "MySQL", "Hostinger"],
    image: "/assets/work/thumb11.png",
    live: "https://verduxe.com/",
    github: "https://verduxe.com/",
  },
  {
    num: "09",
    category: "Full stack",
    title: "Westago",
    description: "Site web de Westago.",
    stack: ["WordPress", "Next.js", "Laravel", "GitHub"],
    image: "/assets/work/thumb11.png",
    live: "https://westago.com/",
    github: "https://westago.com/",
  },
  {
    num: "10",
    category: "Mobile App",
    title: "Manitese PFNL",
    description: "Application mobile de suivi PFNL-PUBW.",
    stack: ["React Native", "Laravel", "GitHub"],
    image: "/assets/work/thumb10.png",
    live: "https://play.google.com/store/apps/details?id=com.legrand_web_services.manitese&hl=en-US",
    github: "https://play.google.com/store/apps/details?id=com.legrand_web_services.manitese&hl=en-US",
  },
  {
    num: "11",
    category: "Mobile App",
    title: "YESIFAN",
    description: "Application mobile de rencontres YESIFAN.",
    stack: ["React Native", "Node JS", "Laravel", "GitHub", "Mogoose DB"],
    image: "/assets/work/thumb10.png",
    live: "https://legrandwebservices.com/",
    github: "#",
  },
   {
    num: "12",
    category: "Mobile App",
    title: "Koum'a fin",
    description: "Application mobile de fintech Koum'a fin.",
    stack: ["React Native", "My Sql", "Laravel", "GitHub"],
    image: "/assets/work/thumb10.png",
    live: "https://www.koumafin.com/",
    github: "#",
  },
    {
    num: "13",
    category: "Site web vitrine / e-commerce",
    title: "Alpha centre visuel",
    description: "Site web de presentation de produits",
    stack: ["WordPress", "Hostinger", "My Sql"],
    image: "/assets/work/thumb11.png",
    live: "https://alphacentrevisuel.com/",
    github: "#",
  },
];